kickstart_devices:
- hostname: kiosk.localdomain
  storage:
    root_disk: /dev/disk/by-path/pci-0000:00:12.0-ata-1
  network:
    interface: enp1s0
    ip_address: 192.168.122.23
    netmask: 255.255.255.0
    gateway: 192.168.122.1
    dns: 192.168.122.1
