- name: Build the RPMS
  hosts: all
  tasks:
    - name: Install software
      become: true
      ansible.builtin.dnf:
        name:
          - git
          - rpm-build
          - rpmdevtools
        state: present
    - name: Clear directory /tmp/images/
      ansible.builtin.file:
        path: /tmp/images/
        state: absent
