- name: Generate the Installer ISO image
  hosts: all
  vars_files: ../credentials.yaml
  tasks:
    - name: Clear /tmp/microshift_bluprint.toml
      ansible.builtin.file:
        path: /tmp/microshift_bluprint.toml
        state: absent
    - name: Create /tmp/microshift_bluprint.toml
      ansible.builtin.file:
        path: /tmp/microshift_bluprint.toml
        state: file
        mode: "0755"
    - name: Write blueprint content to /tmp/microshift_bluprint file
      ansible.builtin.copy:
        dest: "/tmp/microshift_blueprint.toml"
        content: |
          name = "microshift-installer"

          description = ""
          version = "0.0.0"
          modules = []
          groups = []
          packages = []
      become: true

      
    - name: Push Blueprint
      infra.osbuild.push_blueprint:
        src: "/tmp/microshift_blueprint.toml"

    - name: Start OSTree Compose
      ansible.builtin.shell: 
        cmd: composer-cli compose start-ostree --url http://{{ ansible_default_ipv4.address }}/repo --ref empty microshift-installer edge-installer | awk '{print $2}'
      register: build_id


    - name: Wait for compose to finish
      infra.osbuild.wait_compose:
        compose_id: "{{build_id.stdout_lines | first}}"
        timeout: 3600
