- name: Setup VM
  hosts: all
  become: true
  tasks:
    - name: Install software
      ansible.builtin.dnf:
        name:
          - osbuild-composer
          - composer-cli
          - cockpit-composer
          - git
          - podman
          - buildah
          - nginx
          - firewalld
        state: present
    - name: Config services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - osbuild-composer.socket
        - cockpit.socket
        - nginx.service
        - firewalld
    - name: Add user to weldr group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: weldr
        append: true
