#!/bin/sh

set -Eeuo pipefail

# Set the keyboard to French layout
setxkbmap -model pc104 -layout fr,fr

while ! curl -sf --connect-timeout 5 --expect100-timeout 5 --resolve "$KIOSK_HOSTNAME:443:$KIOSK_IP" "$KIOSK_URL"; do
    echo "Waiting for the Kiosk APP to become available..."
    sleep 10
done

exec /usr/bin/google/chrome/chrome --host-resolver-rules="MAP $KIOSK_HOSTNAME $KIOSK_IP" --password-store=basic --no-default-browser-check --no-first-run --ash-no-nudges --disable-search-engine-choice-screen -kiosk "$KIOSK_URL"
